databases:
  - name: moneymap-postges-sql
    plan: free
    databaseName: moneymap
    user: moneymap_user

services:
  - type: web
    plan: free
    name: MoneyMap
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
