# Generated by Django 5.1.1 on 2024-11-04 11:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalAllocation',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='name',
        ),
        migrations.AddField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(default='No description', max_length=255),
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
