# Generated by Django 5.1 on 2024-11-02 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalAllocation',
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(default='No description.', max_length=255),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SavingEntry',
        ),
    ]
