# Generated by Django 5.1.1 on 2024-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='goal',
            field=models.ManyToManyField(blank=True, to='moneymap.goal'),
        ),
        migrations.DeleteModel(
            name='SavingEntry',
        ),
    ]
